### ISSUE TITLE
Inventories going missing after matches

### ISSUE THREAD

**Issue by Zach443** [BattlePluginsDev/BattleArena#11]
Multiple users have reported that after their players' inventories are not being restored after matches. Evidence in multiple comments on the BattleArena2 page, as well as IRC.

(Details coming soon, just created this real quick as a place holder)

**Comment by Europia79** [comment]
http://dev.bukkit.org/bukkit-plugins/battlearena2/?page=10#c180

> So...for some reason, when the players are done with the battle and leave the ARENA gamemode, their inventory is gone. - *AdamTragedy*

http://pastebin.com/fh05AbqQ

I solved this issue a long time ago (i think in IRC or PM)... Just updating everyone else here: This is caused by a mis-configuration of BattleArena. This is caused by ```onComplete: [clearInventory]```

It should be ```onLeave: [clearInventory]```
