### ISSUE TITLE
Class signs too restrictive

### ISSUE THREAD

**Issue by tara81** [BattlePluginsDev/BattleArena#18]
Says I cannot change classes after switching items, when I haven't switched items... Very hard to change classes

**Comment by Europia79** [comment]
For ```config.yml``` change ```needSameItemsToChangeClass: false```

The default is true, which makes it more restrictive. Changing it to false will make it less restrictive.

There's also an option for adding a cooldown when changing classes.

**Comment by tara81** [comment]
sorry I didn't know !
