### ISSUE TITLE
mc.alk.arena.controllers.messaging.MatchMessageImpl

### ISSUE THREAD

**Issue by Kainzo** [BattlePluginsDev/BattleArena#7]
https://www.irccloud.com/pastebin/CCUgYRqe

Seeing this on Spigot 1.8 and latest BA2 (3.9.9.11)

**Comment by Europia79** [comment]
I just took a quick glance at the code... Are any of your config files empty ?

Cause, basically, what it's saying is that you're missing the yaml node "match.interval_update" inside messages.yml &/or messages/DefaultMessages.yml

This is the default key-value pair:
'''
match:
    interval_update: '{prefix} Game ends in {time}.'
'''

**Comment by Zach443** [comment]
The only thing that I could think of that would cause that is your 'interval_update:' is blank. I would suggest checking that in your messages.yml

**Comment by Kainzo** [comment]
http://pastie.org/private/dfqjbwl9zl1uh6e78zt3a 
This was my messages.yml 
I didn't see it.
