### ISSUE TITLE
3.9.9.13 Update breaks plugin, plugin.yml error

### ISSUE THREAD

**Issue by Zach443** [BattlePluginsDev/BattleArena#8]
Just downloaded the 3.9.9.13 jar for testing purposes, and I found that there is an issue with the plugin.yml. @Europia79 I was wondering if you moved it recently? The error appears to be saying that the file can not be found. 

http://paste.battleplugins.org/view/fb1b217b#Zz5cze3J2eykoSmxTfKc3yAV0M3V6xaW

**Comment by Europia79** [comment]
Use 7zip or JD-GUI to look inside the JAR.

Alternatively, you can change the .jar extension to .zip then extract it to view the contents.

I just opened the JAR both ways, the plugins.yml is there.
It also works fine for me.
